name: Ejecutar Notebooks

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      # 📥 Clonar repo
      - name: Clonar repositorio
        uses: actions/checkout@v4

      # 🔍 Debug (ver archivos)
      - name: Ver estructura
        run: ls -R

      # 🐍 Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 📦 Dependencias
      - name: Instalar dependencias
        run: pip install pandas openpyxl notebook

      # ▶️ Ejecutar notebooks
      - name: Ejecutar notebooks
        run: |
          jupyter nbconvert --to notebook --execute Actividad_1_infraV2.ipynb --output Actividad_1_infraV2_out.ipynb
          jupyter nbconvert --to notebook --execute Act2V2.ipynb --output Act2V2_out.ipynb

      # 🔍 Ver archivos generados
      - name: Ver archivos generados
        run: ls -R

      # 💾 Commit y push
      - name: Guardar resultados en repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add *_out.ipynb

          git commit -m "Notebooks ejecutados automáticamente" || echo "Sin cambios"

          git push
