name: Ejecutar Notebooks

on:
  push:
  workflow_dispatch:

jobs:
  notebook1:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repo
        uses: actions/checkout@v4

      - name: 🔍 Ver estructura (debug)
        run: ls -R

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 📦 Instalar dependencias
        run: pip install pandas openpyxl notebook

      - name: ▶️ Ejecutar notebook 1
        run: |
          jupyter nbconvert --to notebook --execute  Actividad_1_infra1V2.ipynb
          --output Actividad_1_infra1_out.ipynb

      - name: 💾 Guardar resultado
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Actividad_1_infra1_out.ipynb
          git commit -m "Notebook 1 ejecutado" || echo "Sin cambios"
          git push

  notebook2:
    runs-on: ubuntu-latest
    needs: notebook1

    steps:
      - name: 📥 Clonar repo
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 📦 Instalar dependencias
        run: pip install pandas openpyxl notebook

      - name: ▶️ Ejecutar notebook 2
        run: |
          jupyter nbconvert --to notebook --execute act2.ipynb
          --output act2_out.ipynb

      - name: 💾 Guardar resultado
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add act2_out.ipynb
          git commit -m "Notebook 2 ejecutado" || echo "Sin cambios"
          git push
